### ISSUE TITLE
unique_hstring and shared_hstring don't manage HSTRING reference counts properly

### ISSUE THREAD

**Issue by DefaultRyan** [microsoft/wil#107]
`unique_hstring` is prone to overrelease when used with a raw HSTRING or with WRL's HSTRING wrappers. This is a pernicious issue that is causing memory corruption and crashes in code that is migrating from WRL toward WIL.

```
{
  Microsoft::WRL::Wrappers source_str = something();
  wil::unique_hstring dest_str =source_str.Get(); // No call to WindowsDuplicateString!
} // At destruction, two calls to WindowsDeleteString are made, causing an overrelease.
```

`shared_hstring` also suffers from this problem, but compounds it with a major performance penalty, because it's creating a `std::shared_ptr` to manage the lifetime of the `HSTRING`, giving us a redundant reference count, instead of just using `WindowsDuplicateString` to properly copy strings around.

**Comment by dunhor** [comment]
Hmm, I wouldn't expect that example to compile since the constructor is marked `explicit`. But the missing call to `WindowsDuplicateString` is intentional and adding it now would break far more consumers than it would fix

And my vague understanding of `shared_hstring` is that its usefulness was primarily for lambda capture, now obsolete.
