### ISSUE TITLE
Strongly-typed resources

### ISSUE THREAD

**Issue by gix** [microsoft/wil#129]
While investigating whether I could replace my own resource wrappers with `wil` I noticed that there aren't any specific strongly-typed wrappers. Although many wrappers are indeed incompatible due to different underlying policy template instantiations, stuff like process, thread, token or timer queue handles are all interchangeable. Is this something that was deliberately decided against or is seen as adding no value?

**Comment by dunhor** [comment]
I can't speak for anyone else, but I suspect the answer is that it wouldn't add much value. The types are mostly used for storage, so beyond initialization, the type isn't very important, nor would it give you any safety since the underlying type is the same in all cases.

The obvious asterisk is testing for validity (IIRC some pseudo handles use -1, unfortunately), but that's a problem at declaration, not usage, so a well named typedef would be just as helpful as a distinct type.

**Comment by oldnewthing** [comment]
I agree with @dunhor. Even if you had separate types `unique_process_handle` and `unique_thread_handle`, there would be no way of preventing you from using the wrong handle:

```cpp
wil::unique_process_handle process{ ... };
SuspendThread(process.get()); // no way to prevent this
```

If it makes you feel better, you could write

```cpp
using unique_process_handle = unique_handle;
using unique_thread_handle = unique_handle;
```

but be honest with yourself and understand that you are not getting any type safety.

**Comment by dimhotepus** [comment]
We also prefer strongly typed resources, so decided to go further and wrap low-level `unique_handle` wrappers again into domain classes, like:

```
namespace windows {
class Thread {
   // Establish and check `unique_handle` invariant via factory method, so `Thread` always has correct handle.         

  Thread(Thread &&) ...

  DWORD Suspend() const noexcept {
      return SuspendThread(handle_.get());
  }

private:
    Thread() ...
    unique_handle handle_;
}
}
```

Pros are:
* Static type safety with all the goodies: impossible to use incompatible handle in a wrong place, better IntelliSense support due to known scope, easier to guess semantic (consider `Process child` vs `unique_handle child_process`), better static analysis support with custom rules on domain classes usage and more.
* If we make methods virtual, mocking and testing becomes much more easier (certainly, with some runtime cost).
* Easy to find and extend APIs, as each OS resource represented via single wrapper in a known place.
* Don't need to wait till WIL adds new shiny wrapper or extension, hence WIL still is thin and lightweight :).

Cons are:
* Need to write wrapper for every single method consumers are going to use. If `unique_handle` is exposed, static type safety is effectively lost.
* Adding new method leads to recompilation of header dependents graph.

**Comment by jonwis** [comment]
I'm going to close this as won't-fix. Feel free to send a PR for wrappers on top of `unique_thread` or `unique_key` that provide resource-specific behavior. Consider putting those in a different header other than the lower-level `resource.h` so they can be optionally included.
