### ISSUE TITLE
secure_string is not secure

### ISSUE THREAD

**Issue by computerquip-work** [microsoft/wil#159]
Due to SSO optimizations, simply making an allocator is not good enough for std::basic_string as far as I understand. If a string grows too large, it can leave plain data in the small buffer that is never cleared by the given allocator. If it isn't initially large or doesn't grow large enough, the buffer is never cleared at all.

I *think* secure_vector is fine.

A test case: https://godbolt.org/z/q3hsxe

**Comment by jonwis** [comment]
Tagging @BillyONeal for his wisdom on whether libraries should do work around SSO. I can't find the (long, instructive) thread we had about it last year.

**Comment by BillyONeal** [comment]
I don't know if the idea of "working around" SSO makes sense; I think the entire concept here is somewhat broken. After all, whatever data you put *in* to the secure_string came from somewhere and that's probably not so protected. Command line? Easy to read. File? Already on disk. Network? Network stack isn't doing this kind of zeroing. Moreover, most general string manipulation algorithms aren't going to be careful to "unnecessarily" zero, etc.

If you still want to do something like this you may be able to write your own type that doesn't hand out access to the original string, and which does the zeroing in its destructor.

**Comment by sylveon** [comment]
Relevant conversation: .NET has deprecated their SecureString type entirely a while ago.

https://github.com/dotnet/runtime/issues/30612

**Comment by BillyONeal** [comment]
> Relevant conversation: .NET has deprecated their SecureString type entirely a while ago.

Ouch, and .NET was one of the few places where this could have theoretically made sense, given strings there are immutable and thus can't be zeroed and all that.

**Comment by jonwis** [comment]
Ok. I'm going to close this as won't fix given the context.  If you have need of a "secure zero this when you're done with it" then you'll need to build and manage your own primitives. But you should probably think hard about your threat model if that's the case...

**Comment by computerquip-work** [comment]
Just to clarify my own intentions, the reason I filed a bug is because the type didn't do as advertised and I felt it was a touch misleading. I'm fine with nothing becoming of this but I do think a deprecation would also be reasonable.

**Comment by sylveon** [comment]
> Ouch, and .NET was one of the few places where this could have theoretically made sense, given strings there are immutable and thus can't be zeroed and all that.

The reasoning was very similar to what you mention here - it was pointless if the SecureString was built from an existing string, or the SecureString was converted to a normal string for interop. Without full vertical integration (which was very unlikely, since most libraries don't support it), it gave a false sense of security.

The suggested replacement was a feature where the entire GC zeroes out stuff on heap compaction, which is more universal (since it applies to string too).

---

FWIW I inherited some legacy C++ code with a custom SecureStringW implementation and while it doesn't use std::string internally, it's as ineffective because it's always constructed from a normal string that came straight from C# (passed through WinRT HSTRINGs, which also doesn't securely clear them AFAIK).
