### ISSUE TITLE
[Request for comments] wil::unique_string

### ISSUE THREAD

**Issue by sylveon** [microsoft/wil#30]
While trying to add support for conversion to `std::string_view` to `unique_any_t` when used to hold strings, I faced multiple issues that prevented me from correctly implementing it without creating a dependency on `<string_view>` or causing a static assertion/ugly `basic_string_view` error when trying to convert non character types to `string_view`. To fix this issue (and add more functionality), I have the idea of creating a unique_string type, which would look somehow like this:

```cpp
template<...>
class unique_string : public unique_any_array_ptr<...>
{
    static_assert(/* that ValueType is a wchar_t or char */);

    // avoid code duplication, reuse constructors from inherited class
    using unique_any_array_ptr<...>::unique_any_array_ptr;

    // somehow enabled conditionally
    operator std::basic_string_view<value_type>() const { return { this->get(), this->size() }; }

    const_pointer c_str() const { return this->get(); }
    size_type length() const { return this->size(); }

    // maybe more string manipulation functions?
}
```

All the existing type aliases and string helpers would be updated to use this type instead. This would allow for things like correctly embedding null characters, bounds checked string access, and being able to pass the string RAII wrappers to functions accepting string views.

I believe that after updating everything, this shouldn't break normal usage cases, because `unique_string` will end up exposing the same API surface than `unique_any` via public inheritance of `unique_array_ptr`.

As a bonus some Natvis visualizers for `unique_string` could be made so that it shows up nicely in a debugger.

I'm submitting this as request for comments since this would be a pretty major change, so I want to get comments or check if this would even be accepted before getting to work implementing it.

**Comment by dunhor** [comment]
Anything that has a dependency on the STL needs to be relatively isolated. This is especially true when taking a dependency on newer STL features (I don't recall exactly which STL versions are used in the Windows build, but anything newer than C++11 generally requires caution). So as its own standalone thing, likely in a separate header that nothing else depends on is probably fine. That is, if the value added is worth having yet another string type.

**Comment by sylveon** [comment]
This is where `std::string_view` comes in, at least for C++17 users. It's a non-owning string type, so it allows to write functions that accept many string types without the need to be templated. Obviously would need to be properly checked for availability before being used.

```cpp
void print(std::wstring_view text)
{
    std::wcout << text;
}

print(L"foo"); // ok

const std::wstring str(L"bar");
print(str); // ok

const auto costr = wil::make_cotaskmem_string(L"baz");
print(costr); // would also be ok
```

**Comment by ChrisGuzak** [comment]
string_view is awesome, so if we can make wil work well with it that would be valuable.

**Comment by sylveon** [comment]
I do see one issue with my approach: some APIs don't allow you to pass the address of a size type and instead leave the caller figuring out the size by using `strlen` or some other method, effectively making bounds-check ineffective or wrong on `unique_array_ptr` because the internal size isn't updated.

This could probably be worked around by adding a function to update the internal size based on the string's length (determined by the null-terminating character), but that function would need to be manually called after the fact. Another possible option is to use a proxy struct, not unlike `size_address_ptr`, that would automatically recompute the length once it's destroyed. It would require explicitely calling a function with another name (`put_with_length()`?) since we can't overload on return types only, and that proxy struct's behavior may not always be desired, like in the cases where a function does accept a pointer for the string size, in case there's embedded nulls.

Some also return the length of the string I believe, but this would already be workable with
```cpp
*str.size_address() = LoadMyString(str.put());
```

As a sidenote, `wil::str_raw_ptr` and `wil::details::string_maker` would also need to be updated for unique_string.

**Comment by ChrisGuzak** [comment]
the problem of needing to re-size strings leads to a few known bugs for string types that use a length value instead of the nul terminator. HSTRING and std::wstring for example (these types support embedded nulls, a rarely useful and in some uses not allowed). this manifests in incorrectly formed strings but often we don't suffer as the consumers take the nul terminated view.

there are cases where std::wstring::size() is out of sync with the length determined by the nul terminator ([this OS bug](https://dev.azure.com/microsoft/OS/_queries/edit/17684636/?triage=true)).

this is exacerbated by some of the Win32 APIs that won't tell you the size up front before you allocate, you need to over-allocate, then get the value and at that point you know the size. RegQueryValue for REG_SZ that may or may not be null terminated (we need to add a flag to that API to tame this behavior).

to address this we need to make the wil types have a .resize() but this has to be optional as HSTRING does not support it.

perhaps using if constexp on tag types [like Kenny does in C++ WinRT ](https://github.com/microsoft/xlang/blob/f8bfe930beb330f541c179bc5b4e7ab70734e91e/src/tool/cppwinrt/strings/base_implements.h#L1215) to enable an optional reset() (and block use of forms that don't in APIs that don't support it).

**Comment by ChrisGuzak** [comment]
one more thing, `<wil/stl.h>` can be used for STL specific stuff

**Comment by sylveon** [comment]
Dropped the idea, this proved too complex and would probably not cover all use cases. It's easier to just use the right string length call manually to then drop it in a wstring_view and do all the manipulation using that.
