### ISSUE TITLE
Documentation says unique_variant is a unique_any but it's a unique_struct.

### ISSUE THREAD

**Issue by parkrrrr** [microsoft/wil#61]
The wiki says that unique_variant is derived from unique_any, but it's actually derived from unique_struct. Among other things, this means that to get a raw VARIANT the correct thing to do is a static_cast, because get() is not implemented. (And there is no shared_variant, for obvious reasons.)

I would make the change to the wiki myself, but I'm not sure that there aren't other similar issues with other types, and I'm not sure how unique_variant (and any other wrappers with the same issue) should be mentioned relative to the current documentation for unique_struct.

**Comment by jonwis** [comment]
unique_struct says:

``` c++
    template <typename struct_t, typename close_fn_t, close_fn_t close_fn, typename init_fn_t = wistd::nullptr_t, init_fn_t init_fn = wistd::nullptr_t()>
    class unique_struct : public struct_t
```

So a `unique_variant` is-a `VARIANT`, and you can pass it to things that need to accept both `VARIANT` and `VARIANT*`.  I'll fix the documentation for the type and will push up a test that enforces this behavior.

**Comment by jonwis** [comment]
Rereading the wiki, I can't find anywhere that says `unique_variant` derives from `unique_any` ... the closet I can find is this in the section about the various `array_ptr`-like things:

> For unique_any-derived types, unique_struct-derived types, and com_ptr, the elements are destructed according to the rules for that type, and then the entire array is freed with CoTaskMemFree.

So a `wil::unique_muffinmem_array_ptr` will invoke the dtors on the contained items _in the usual way_ and then call `FreeMuffinMem` on the underlying array pointer.  That's goodness, because `FreeMuffinMem` doesn't know it's being asked to free an array of types with destructors; wil's adapter tracks this and does the right thing.

Can you point me at the problematic section of the wiki to review?

**Comment by parkrrrr** [comment]
Yep, it's listed in the table here:

https://github.com/microsoft/wil/wiki/RAII-resource-wrappers#available-unique_any-handle-types

**Comment by parkrrrr** [comment]
Of additional concern is that if I recall correctly, it's only listed in that table, so to figure out how it really works, you have to use the source.

**Comment by jonwis** [comment]
Aha! I was digging in the wrong place! Ok, I've updated the wiki so the `unique_struct` ones are in the right table. Are you looking for in-wiki samples of using the types?

**Comment by parkrrrr** [comment]
Nope, I think what's there should be sufficient. I was just led astray by their being in the other table. I think you've fixed it, and I'll close this issue. Thanks!
